
---
- name: install HTTP server
  hosts: n2
  become: yes
  tasks:
    - name: install HTTPD
      dnf:
        name: httpd
        state: present

    - name: start httpd
      service:
        name: httpd
        state: started

    - name: Enable httpd
      service:
        name: httpd
        enabled: yes
        
...