---
- name: Variables Demo
  hosts: g3
  become: yes
  vars:
    myusername: Hi-bibi

  tasks:
    - name: Update Dynamic page
      template:
        src: dynamic.j2
        dest: /var/www/html/dynamic.html
...